### PR TITLE
adding interactive stats to instance stats

### LINKED ISSUE #892: Instance stats interactive monitoring
**Is your feature request related to a problem? Please describe.**

The `instance stats` command shows a point-in-time snapshot of instance resource usage. Often we really want to monitor how resource use is changing.

**Describe the solution you'd like**

Running the `instance stats` command should default to an interactive mode, where the resource usage is displayed, updated every second, until the user exits wtih Ctrl+c.

There should be a `--no-stream ` flag (compatible with the docker/podman CLI) to disable this interactive mode. With `--no-stream` the behavior should be as it is now - show the point-in-time usage, and exit.

**Additional context**

This is CLI level functionality to be implemented in `cmd/internal/cli/instance_stats_linux.go`.

### PR DESCRIPTION
**Pull request by vsoch**
## Description of the Pull Request (PR):

This PR will add streaming stats, meaning that we get (and refresh) stats each second on a running instance instead of showing one timepoint. The default will be to stream stats for an instance, meaning pinging for an update every second. If --no-stream is added we only print one timepoint.

Here is how I tested locally:

```bash
cd ./builddir
make
```
```bash
$ touch null.toml
$ sudo singularity instance start --apply-cgroups null.toml docker://busybox test
```
```bash
$ sudo ./singularity instance stats test 
```

And then stream!

```bash
$ sudo ./singularity instance stats test
INFO:    Stats for test instance of /root/.singularity/cache/oci-tmp/3614ca5eacf0a3a1bcc361c939202a974b4902b9334ff36eb29ffe9011aaad83 (PID=1257775)
INSTANCE NAME    CPU USAGE    MEM USAGE / LIMIT    MEM %    BLOCK I/O    PIDS
test    55749960 ns    6.027MiB / 15.33GiB    0.04%    522KiB / 0B    7
test    55749960 ns    6.027MiB / 15.33GiB    0.04%    522KiB / 0B    7
test    55749960 ns    6.027MiB / 15.33GiB    0.04%    522KiB / 0B    7
test    55749960 ns    6.027MiB / 15.33GiB    0.04%    522KiB / 0B    7
test    55749960 ns    6.027MiB / 15.33GiB    0.04%    522KiB / 0B    7
test    55749960 ns    6.027MiB / 15.33GiB    0.04%    522KiB / 0B    7
test    55749960 ns    6.027MiB / 15.33GiB    0.04%    522KiB / 0B    7
test    55749960 ns    6.027MiB / 15.33GiB    0.04%    522KiB / 0B    7
test    55749960 ns    6.027MiB / 15.33GiB    0.04%    522KiB / 0B    7
^CINFO:    Detected Control + C, exiting.
```
I also shelled in and made sure to goof off a bit to ensure that the stats were updating (they were).

### This fixes or addresses the following GitHub issues:

 - Fixes #892 

I'm not sure if we can reasonably test for an interactive thing, but let me know if you have ideas!

### CODE REVIEW

**Comment by dtrudg** [comment]
Hi @vsoch - it looks like when you ran the license deps update it removed all the auto-generated license text. Did you see any errors running the script? Something has gone wrong so I'd like to get that fixed, for sure.

**Comment by vsoch** [comment]
You're right - it was choking on something in the builddir (and I totally missed it!) Removing the directory and running again seemed to work.

**Review by dtrudg — APPROVED** [review]

**Comment by dtrudg** [comment]
Thanks again @vsoch

**Comment by vsoch** [comment]
yay!

**Pull request merged**
