### PR TITLE
Migrate to gopkg.in/yaml.v3

### LINKED ISSUE #1217: Migrate to gopkg.in/yaml.v3
We should migrate to yaml.v3 to be assured that our dependency is maintained going forward.

See: https://github.com/go-yaml/yaml

There is limited use in the code base, but some minor changes are likely to be required.

```
internal/pkg/remote/remote_test.go
18:	yaml "gopkg.in/yaml.v2"

internal/pkg/remote/remote.go
22:	yaml "gopkg.in/yaml.v2"

internal/app/singularity/remote_add_test.go
15:	"gopkg.in/yaml.v2"
```

### PR DESCRIPTION
**Pull request by michaelRichards99**
## Description of the Pull Request (PR):

Updates the Go dependency to [yaml v3](https://gopkg.in/yaml.v3).

### This fixes or addresses the following GitHub issues:

 - Fixes #1217

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Review by dtrudg — CHANGES_REQUESTED** [review]
You will need to run `go mod tidy` and commit the resulting changes to `go.sum`. Thanks.

**Comment by michaelRichards99** [comment]
I ran `go mod tidy` in the most recent commit. Nothing changed in the `go.sum` file though (looks like yaml.v3 v3.0.1 is already represented in the go.sum file).

**Comment by dtrudg** [comment]
Okay - thanks...  that was my thought for why the dependencies file was wrong, but it looks like there was a different cause that you've worked out.

**Review by dtrudg — APPROVED** [review]
:+1: Thanks!

**Pull request merged**
