### PR TITLE
adding support for test to have a custom shell

### PR DESCRIPTION
**Pull request by vsoch**
Akin to start and run, a user might want a test file to use a custom hashbang. This was basically all ready to go and just needed to be extended to the test script! I was not sure where to write tests so I will wait for guidance on that.

This request came from Twitter! https://twitter.com/ifndef_define/status/1536689964225908737 As I noted above I still need to add a test, and will do so with further guidance. I indeed have tested manually/locally and it looks good! :partying_face: 

image

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by dtrudg** [comment]
Hi @vsoch - there isn't actually a great place to test the full functionality of this in the e2e suite at present. I will open a 'technical-debt' issue mentioning that the e2e tests should be extended to cover custom shebangs for the definition file scripts.

What we do have is a place where we unit-test the parsing of definition files:

https://github.com/sylabs/singularity/blob/d1408d7ed5ac971cf61a649d02839b331b076bf9/pkg/build/types/parser/deffile_test.go#L191

You'll see the test case line above references a definition fle, and the JSON output that is expected when parsing it. We need a similar separate case (with a def file and expected JSON output) for when the test section has a custom shebang.

Note that when developing this test it's easy to run the test as it is unit, not e2e:

```
go test -v ./pkg/build/types/parser/...
```

Some general comments:

* When you submit a PR for n enhancement or bugfix, please add an entry to the `CHANGELOG.md` in a `New Features and Functionalities` or `Bug Fixes` header as appropriate.
* If you could create an issue which captures the problem/request before opening the PR, that would be much appreciated as a fairly strict issue->PR mapping helps us manage roadmap / milestone / release things.

Thanks for the contribution as ever!

**Comment by vsoch** [comment]
Will do! Sorry for the missing bits, this was a post dinner "oooh this would be fun!" and I did look briefly into testing and figured it would be easier to just ask you! Changes coming soon!

**Comment by dtrudg** [comment]
I've added the `ci:e2e` label to this PR and re-started CI. This is so that the e2e tests run. CI is setup to skip the e2e tests if e2e tests or dependencies are  not modified. However, sometimes, like this one... we want to ensure all the e2e test still pass before merging.

**Comment by dtrudg** [comment]
The e2e test failure here is:

```
=== CONT  TestE2E/PAR/BUILD/issue_4967
    singularitycmd.go:689: 
        "/usr/local/bin/singularity build /tmp/stest.3431533088/issue_4967.sif testdata/regressions/issue_4967.def" output:
        INFO:    Starting build...
        Getting image source signatures
        Copying blob sha256:396c31837116ac290458afcb928f68b6cc1c7bdd6963fc72f52f365a2a89c1b5
        Copying config sha256:0d6a06850d884f7107d50d51e0bccf9b0c9d265eea3715035b9423831e8f4baf
        Writing manifest to image destination
        Storing signatures
        2022/06/15 18:05:07  info unpack layer: sha256:396c31837116ac290458afcb928f68b6cc1c7bdd6963fc72f52f365a2a89c1b5
        INFO:    Running post scriptlet
        + apk add --update-cache bash
        INFO:    Adding testscript
        INFO:    Running testscript
        /bin/sh: illegal option - 
        FATAL:   While performing build: failed to execute %test script: exit status 2
        fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
        fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
        (1/4) Installing ncurses-terminfo-base (6.1_p20190518-r2)
        (2/4) Installing ncurses-libs (6.1_p20190518-r2)
        (3/4) Installing readline (8.0.0-r0)
        (4/4) Installing bash (5.0.0-r0)
        Executing bash-5.0.0-r0.post-install
        Executing busybox-1.30.1-r5.trigger
        OK: 8 MiB in 18 packages
        
    singularitycmd.go:689: got 255 as exit code and was expecting 0: exit status 255
        waiting for command "/usr/local/bin/singularity build /tmp/stest.3431533088/issue_4967.sif testdata/regressions/issue_4967.def"
        github.com/sylabs/singularity/e2e/internal/e2e.TestEnv.RunSingularity.func1
        	github.com/sylabs/singularity/e2e/internal/e2e/singularitycmd.go:664
        github.com/sylabs/singularity/e2e/internal/e2e.Privileged.func1
        	github.com/sylabs/singularity/e2e/internal/e2e/priv.go:63
        github.com/sylabs/singularity/e2e/internal/e2e.TestEnv.RunSingularity.func2
        	github.com/sylabs/singularity/e2e/internal/e2e/singularitycmd.go:689
        runtime.goexit
        	runtime/asm_amd64.s:1571
```

This is an e2e test that is intending to ensure that `-c` args on a `%post` or `%test` line work. On looking into this quickly, I can see that the e2e test isn't  *actually* successfully verifying `-c` works with `%test` and indeed it doesn't....

```
$ cat test.def 
Bootstrap: docker
From: fedora:35

%test -c /bin/bash
echo SHELL
echo $SHELL
echo CMDLINE
cat /proc/$$/cmdline | tr '\000' ' '

%post -c /bin/bash
echo SHELL
echo $SHELL
echo CMDLINE
cat /proc/$$/cmdline | tr '\000' ' '
```

```
 $ sudo singularity build test.sif test.def
Build target 'test.sif' already exists and will be deleted during the build process. Do you want to continue? [N/y] y
INFO:    Starting build...
Getting image source signatures
Copying blob 054e3e802ba7 skipped: already exists  
Copying config 04d13a5c8d done  
Writing manifest to image destination
Storing signatures
2022/06/15 13:22:41  info unpack layer: sha256:054e3e802ba7bde57dcc19df7b12ac4fecb92bc0c3e7b591210bcea96f993b5d
INFO:    Running post scriptlet
+ /bin/bash /.post.script
SHELL
/bin/bash
CMDLINE
/bin/bash /.post.script INFO:    Adding testscript
INFO:    Running testscript
SHELL
/bin/bash
CMDLINE
/bin/sh /.singularity.d/test INFO:    Creating SIF file...
INFO:    Build complete: test.sif
```

Now stepping back from this, we unfortunately get into some weeds with how singularity runs scripts.

* %post is only run through the build engine
* %runscript and %startscript (working with the hashbang processing) are only called on container invocation
* %test is run through the build engine *or* through `singularity test` after the container is built.

The `%test -c` construct would only work in a definition file... if you could do `%test  -c /bin/csh` then it'd only apply in the build where that arg is present. It would not apply when you do `singularity test` and we are just running the `/.singularity.d/test script`.

I think we need to drop `-c` support (which anyway is currently broken) for `%test`, and just support the hashbang model you are trying to implement here. 

I need to look into this a bit more... but I think we definitely have a bug here which is not related to your changes.

**Comment by vsoch** [comment]
@dtrudg from the source code I got the impression that the -c doesn't actually work, but instead the script parsing expects the shebang to just be at the top. At least I didn't see anywhere in the source code for -c to work.

**Comment by dtrudg** [comment]
@vsoch yeah, the `%test -c` doesn't work... but there's a regression test that purports to test it does work. Also, we run differently in a build vs a `singularity test` which we need to sort out as it'll impact the hashbang working or not.

I've written it up as #871 ... basically we need to unpick a little bit of stuff there, and then this PR will all fall out working... the hashbang handling you are implementing is definitely what makes sense here.

**Comment by dtrudg** [comment]
@vsoch - okay, if you rebase on / merge from main then what has been done in #872 should :crossed_fingers: make this a passing PR on the e2e-tests.

**Comment by vsoch** [comment]
rebase failed, but I'll pull changes instead.

**Review by dtrudg — APPROVED** [review]

**Comment by vsoch** [comment]
Hooray!

**Pull request merged**
